apiVersion: apps/v1
kind: Deployment
metadata:
  name: analogmonitor-be-30088
  namespace: boat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analogmonitor-be-30088

  template:
    metadata:
      labels:
        app: analogmonitor-be-30088

    spec:
      containers:
      - name: analogmonitor-be-30088

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom: 
        - secretRef: 
            name: analogmonitor-be-30088-secret