apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: analogmonitor-be-30088
  namespace: boat

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: analogmonitor-be-30088-secret
    creationPolicy: Owner

  dataFrom:
  - extract:
      key: apps/analogmonitor-be-30088
