apiVersion: v1
kind: Service
metadata:
  name: analogmonitor_be_30088
  namespace: boat

spec:
  type: NodePort

  selector:
    app: analogmonitor_be_30088

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088