apiVersion: apps/v1
kind: Deployment
metadata:
  name: analogmonitor-fe-30087
  namespace: boat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analogmonitor-fe-30087

  template:
    metadata:
      labels:
        app: analogmonitor-fe-30087

    spec:
      containers:
      - name: analogmonitor-fe-30087

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom: 
        - secretRef: 
            name: analogmonitor-fe-30087-secret